### ISSUE TITLE
Cannot commit on empty HEAD

### ISSUE THREAD

**Issue by Black-Photon** [SiliconSloth/Metro#15]
## Issue Description
`Git Error: revspec 'HEAD' not found` when attempting to commit on new empty repository.

## Expected Behaviour
Initial commit to be created without error.

## Reproducibility
```bash
git init
touch file
metro commit "Message"
```

## System Details
Ubuntu 18.4

## Release Version
`master` branch commit 129

**Comment by SiliconSloth** [comment]
Fixed in 131d8d0916a0b575320b60a54979458a45e8090d
