### ISSUE TITLE
Syncing a Conflicting WIP Undoes Commits

### ISSUE THREAD

**Issue by Black-Photon** [SiliconSloth/Metro#33]
## Issue Description
With an outdated head, and new info on WIP, syncing causes the new WIP to override the incoming remote commits, causing the next commit to revert their work

## Expected Behaviour
Metro should attempt to merge WIP and remote as if separate conflicting branches.

## Reproducibility
Begin with a branch that has extra commits on remote not on local.
Edit a file locally
```
$ metro sync
$ metro commit
$ metro sync
```

## System Details
Windows 10

## Release Version
`user-experience` branch commit 163

**Comment by SiliconSloth** [comment]
Fixed by f4c9c62
