### ISSUE TITLE
Command: Config

### ISSUE THREAD

**Issue by Black-Photon** [SiliconSloth/Metro#42]
## Command Description
The `metro config` command will allow the user to set config options for Metro.

This will be useful for persistent configuration options not added by Git. Ideally this config should be for the machine rather than the individual repository.

## Expected Behaviour
You could configure metro to automatically create new branches in the case of a sync conflict using `metro config sync_branches on`.

In addition, `metro config -h` should list the config options that can be changed, the values they accept and a description of what they do.

Some examples for config options are:
 - Whether to automatically create branches in case of a conflict
 - Whether to sync WIP branches
 - Whether to automatically add to staging area when using `metro commit`

However such config options should ideally be submitted in new feature requests.

**Comment by SiliconSloth** [comment]
How would this work alongside and improve upon `git config`? Apart from listing the new Metro-specific options this doesn't seem to do much that `git config` cannot?

**Comment by Black-Photon** [comment]
Can `git config` set config for options that don't exist in standard git? The main motivation was for options that can't be set using `git config`

**Comment by SiliconSloth** [comment]
Yes.  You can set whatever config keys you like with `git config`.

**Comment by Black-Photon** [comment]
Oh cool, didn't know that. Let's close this for now then.
