### ISSUE TITLE
Command: Info Changes

### ISSUE THREAD

**Issue by Black-Photon** [SiliconSloth/Metro#44]
## Command Description
The `metro info changes` subcommand will be used to get detailed information about what files have been changes, and in what ways.

## Expected Behaviour
You change some files, but can't remember which ones. You can check by using `metro info changes`. This will list the files, and you can see you added lines to some file.

## Notes
It should also be considered if it would be more appropriate for this to be in normal `metro info`.

**Comment by SiliconSloth** [comment]
Command removed by a47cd79b
