### ISSUE TITLE
Command: List Commits --no-prompt

### ISSUE THREAD

**Issue by Black-Photon** [SiliconSloth/Metro#45]
## Command Description
Currently `metro list commits` will print commits one at a time, asking for user input at each commit.
However, this makes piping into other commands difficult. Thus, an alternative command should exist which prints all commands without prompt.

## Expected Behaviour
You can use `metro list commits --no-prompt | grep "Windows"` to find a list of commit messages regarding windows in bash.

**Comment by SiliconSloth** [comment]
Command removed by a47cd79
