### ISSUE TITLE
Broken remote WIP branch cannot be fixed using Metro

### ISSUE THREAD

**Issue by SiliconSloth** [SiliconSloth/Metro#49]
## Issue Description
Metro currently does not allow syncing of branches for which either the remote or local WIP branch is invalid.  This makes it impossible to fix the remote branch using Metro, as remotes cannot be worked on directly. This in turn totally prevents syncing the branch unless external tools are used.

## Expected Behaviour
Some method to resolve broken WIP branches without resorting to external tools.

## Reproducibility
Make a remote branch with a corrseponding remote WIP branch.  Push a commit to the base branch using a non-Metro tool, such that the WIP commit is no longer a child of the base branch head.  Run `metro sync`.

## System Details
Windows 10

## Release Version
`sync` branch commit #47

**Comment by Black-Photon** [comment]
Making this an enhancement as it is not failing to perform to expected behavior, but that behavior has not yet been written.

**Comment by SiliconSloth** [comment]
Seems similar to #56
