### ISSUE TITLE
Improved Git Sync Compatibility

### ISSUE THREAD

**Issue by Black-Photon** [SiliconSloth/Metro#51]
## Feature Description
Currently `metro sync` uses information about previous sync's in order to decide whether a change was made on the local or remote side. However, when the repo is pushed/pulled with git, this cache is not updated.

Metro should be able to notice that a push/pull has occurred without using `metro sync`, and use relaxed rules in this scenario as information about what was changed is unknown.

## Expected Behaviour
Edit and commit a file and run `git push` in order to push it.
Then delete the branch that was pushed on remote.
Currently, `metro sync` will see you have new commits which conflict with the deletion of the branch. Thus, it will create a new branch and move the local changes there.

Metro should instead notice that `git push` was used, invalidating the sync cache. It should push the branch normally to the remote.

Note: If `metro sync` was used instead of `git push`, it would delete the local branch. However, without the cache being updated, this behaviour cannot be inferred.

**Comment by SiliconSloth** [comment]
This is actually already how Metro is supposed to behave; if a deleted branch is in conflict with a non-deleted version, it should notice and retain the entire branch on both local and remote.  The only case in which Metro does not do this currently, instead making a separate conflict branch as you describe, is if the branch had an invalid WIP branch last time it was synced; could this be the case here?

**Comment by Black-Photon** [comment]
I don't believe so - No WIP existed on local or remote.
I tested on another branch however and the same didn't occur.
I'll close this for now as something to test further later.
