### ISSUE TITLE
Command: Wip

### ISSUE THREAD

**Issue by Black-Photon** [SiliconSloth/Metro#57]
## Edit
`metro fix` now replaced with `metro wip`

## Command Description
Metro fix is a command that is used to resolve problems involving the WIP. The base command does nothing, however subcommands exist to do further.

## Expected Behaviour
`metro fix branch --squash-wip` will squash all the commits on the WIP branch since the head of the base branch into one valid WIP commit.

`metro fix branch --delete-wip` will delete the WIP branch completely.

`metro fix --export-wip` will disconnect the WIP of the current branch from the working directory to a new branch. Be aware, any changes in the base/workdir after this command will not be saved until it is deleted, or imported.

`metro fix --import-wip` will reconnect the WIP of the current branch, loading the changes into the

**Comment by Black-Photon** [comment]
#### New command specification:
`metro wip delete` will delete the `#wip` for the current branch, but leave the changes in the working directory.
`metro wip restore` will restore the `#wip` to the working directory, deleting changes currently there.
`metro wip squash` will squash the `#wip` and apply it to the working directory if possible.
`metro wip eject` will rename the `#wip` branch into a new branch.
`metro wip save` will save the working directory to the `#wip` branch.

Edit: Rename `fix` to `wip`

**Comment by Black-Photon** [comment]
@SiliconSloth 
Should this command actually be called `metro wip` - it would make it more obvious what the commands are working on?

**Comment by SiliconSloth** [comment]
I was thinking that, `fix` is really vague.  `wip` sounds like a decent alternative.
