### ISSUE TITLE
Command: Switch --wip

### ISSUE THREAD

**Issue by Black-Photon** [SiliconSloth/Metro#59]
## Command Description
This will force move you to the WIP branch of the target branch (or current branch if none) to allow corrective action.

## Expected Behaviour
Somebody committed many changes to the WIP branch by accident. All these changes are needed except for the last, so cannot use `metro fix --squash-wip`. You use `metro switch --wip` to move to the WIP branch, then delete the last command using `metro delete commit`. Finally, you switch back to the main branch, run `metro fix --squash-wip` to merge the other WIP changes and continue work.

**Comment by SiliconSloth** [comment]
As of 450e5a9 `switch` is capable of moving to a WIP branch anyway.
