### ISSUE TITLE
No guide for building Metro

### ISSUE THREAD

**Issue by JorelAli** [SiliconSloth/Metro#7]
Currently, there are no instructions for building Metro. I have tried the following on Ubuntu-18.04:

- Cloning the repository
- Installing `cmake` using `sudo apt install cmake`
- Cloning the [libgit2 repository](https://github.com/libgit2/libgit2)
- Building the libgit2 project (which involved installing `libssl-dev` from apt)
- Adding the libgit2 as an environment variable using `export LIBGIT_PATH=./../libgit2/build`
- Setting the environment variable `export LD_LIBRARY_PATH=./../libgit2/build`
- Setting the environment variable `export LIBGIT2=./../libgit2/build`
- Running `cmake . -DCMAKE_CXX_COMPILER=/usr/bin/c++ -Wno-dev`
- Running `make`

This produces the error `fatal error: git2.h: No such file or directory` in the file `pch.h`:

```
[ 25%] Building CXX object CMakeFiles/metro.dir/src/main.cpp.o
In file included from /mnt/d/Users/Jorel/Documents/GitHub/Metro/src/pch.cpp:1:0,
                 from /mnt/d/Users/Jorel/Documents/GitHub/Metro/src/main.cpp:1:
/mnt/d/Users/Jorel/Documents/GitHub/Metro/include/pch.h:17:10: fatal error: git2.h: No such file or directory
 #include "git2.h"
          ^~~~~~~~
compilation terminated.
CMakeFiles/metro.dir/build.make:62: recipe for target 'CMakeFiles/metro.dir/src/main.cpp.o' failed
make[2]: *** [CMakeFiles/metro.dir/src/main.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/metro.dir/all' failed
make[1]: *** [CMakeFiles/metro.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

A list of build instructions would be very helpful, or a build script.

**Comment by SiliconSloth** [comment]
`LIBGIT_PATH` should point to the `libgit2` directory, not the build directory, other than that your method looks correct.  I will probably add command line build instructions when I have time.

**Comment by SiliconSloth** [comment]
The readme has been updated to have the new build instructions.

**Comment by Black-Photon** [comment]
Also added detailed instructions here: https://github.com/SiliconSloth/Metro/wiki/Install
