### ISSUE TITLE
Switching on headless tag/commit

### ISSUE THREAD

**Issue by Black-Photon** [SiliconSloth/Metro#77]
## Issue Description
When a tag/commit is checked out, attempting to use commands such as `metro branch`, `metro switch` and `metro list branches` will give an error `Branch not found.`

## Expected Behaviour
Commands should operate normally, only giving an error when a current branch being checked out is required.

## Reproducibility
```
$ git checkout tag
$ metro list branches
```

## System Details
Windows 10

## Release Version
Commit 35a995c

**Comment by SiliconSloth** [comment]
This should now work when a commit ID is checked out as of #89, however I'll test whether it also works when tags are checked out later.

**Comment by SiliconSloth** [comment]
Fixed by #92
