### ISSUE TITLE
Why build libgit2 from source?

### ISSUE THREAD

**Issue by JorelAli** [SiliconSloth/Metro#8]
Why does CMAKE expect LibGit2 to be built from source? In a normal installation of libgit2 (say, using `sudo apt-get install` or installing from the AUR), the `libgit2/build` directory is not present. This is required by your CMAKE file:

```
set_target_properties(git2 PROPERTIES IMPORTED_LOCATION "${libgitDir}/build/libgit2.a")
```

Suuuuuuuuuuuurely it would be better to not have to build libgit2 from source, right? _(NixOS user here, building libgit2 from source is a pain)_

**Comment by SiliconSloth** [comment]
I've got this working on my own machine using libgit2 installed via apt, currently working on adapting the CMake file to play nicely with different versions of libgit2 and support both the source and package manager versions.

**Comment by SiliconSloth** [comment]
I've fixed this on master, you should now be able to use libgit2 installed via your package manager.
