### ISSUE TITLE
Absorb WIP

### ISSUE THREAD

**Issue by Black-Photon** [SiliconSloth/Metro#82]
## Feature Description
The absorb command should be able to absorb WIP commits, replaying their changes on top of the current/target branch as required, similar to how `git stash` works. The WIP can be on either or even both branches. Merging conflicts should occur as normal, but NO commits should be created during a WIP merge, as the contents of the WIP's are temporary.

If a both branches have *commit* conflicts as well as WIP's, the branch should be absorbed normally without WIP interference. The WIP's should be applied on top of the final result *after* `metro resolve` is used to finish the merge. The WIP contents will be inaccessible until the merge of the commits is complete.

## Expected Behaviour
```
$ metro branch local-2
$ touch b
$ metro switch local-1
$ metro commit "a"
$ touch a
$ metro absorb local-2
```
This will cause local-2 to disappear, simply moving the WIP commit to local-1 (as no commits since base)

**Comment by SiliconSloth** [comment]
Command removed by a47cd79
