### ISSUE TITLE
[Suggestion] User friendly messages for powerful tasks

### ISSUE THREAD

**Issue by JorelAli** [SiliconSloth/Metro#9]
At the moment, with Git and Metro (currently), there is a lack of "user friendliness" when it comes to "complex" tasks. For example, performing an absorb action can lead to conflicts that require resolving. Sometimes, users may not want the system to do a certain action.

An example of how other programs (namely, the Elm package manager) handles "complex" tasks is to basically give an outline of everything it plans to do, then brings up a confirmation box for the user if that's exactly what they want to do:
![image](https://user-images.githubusercontent.com/4613171/68026323-4f332280-fca7-11e9-89f6-891fd5203d9c.png)

This idea could also be applied to say, branch deletion which is an irreversible action and users may want to have some extra confirmation before a destructive operation occurs.

**Comment by SiliconSloth** [comment]
More helpful messages are something we definitely want to add to Metro in the future, but for now we are focusing our effort on getting the core functionality of the software working.  Once that's done, we should have a better idea of how everything fits together and what the messages should actually say.
